---
- name: Ensure docker-compose is installed
  apt:
    name: docker-compose
    state: present
  become: true

- name: Run docker-compose on VM2
  command: docker-compose up -d
  args:
    chdir: "{{ project_path }}"
