---
# tasks file for project

- name: Ensure project directory does not exist (remove old one)
  file:
    path: "{{ project_path }}"
    state: absent
  ignore_errors: yes   # لو المجلد مش موجود، ما يطلعش خطأ

